### ISSUE TITLE
Point to dedicated Arch wiki section in post_install message

### ISSUE THREAD

**Issue by neitsab** [grazzolini/dropbear_initrd_encrypt#5]
Hi, first of all let me thank you from the bottom of my heart for providing this really useful piece of software. When I first got into full disk encryption and server administration I was worried it'd be a real PITA to remotely unlock a box ([like it seems to be the case on other platforms...](https://unix.stackexchange.com/questions/37024/how-to-open-a-port-early-in-boot-process-to-unlock-luks-via-ssh)), but then I discovered your package and it worked blissfully.

At that time I rewrote the instructions on the Arch wiki to provide detailed step-by-step instructions, after dabbling to figure all the required steps out. Today while upgrading I saw the `post_{install,upgrade}` message again and thought it could be helpful to include a link to this section since it points to every required doc (mkinitcpio hook, ssh keys...).

Here goes the link: https://wiki.archlinux.org/index.php/Dm-crypt/Specialties#Remote_unlocking_of_the_root_.28or_other.29_partition. Please review it and tell me if you think something is missing!

Cheers

**Comment by grazzolini** [comment]
Thank you for the feedback. I have adopted this package because I use it a lot and it wasn't working. I always meant to edit the Specialties page to include the most up to date information regarding this hook. But I'm planning to change this hook to make it more useful, even having a systemd version of it. And probably I'll rename and split it. Since the AUR is being migrated, I'll probably have this done after July 8th.

**Comment by neitsab** [comment]
Good to know. I saw mentions of the incoming plans in the commits but I didn't really grasp what they will change (e.g. what is the interest of a systemd version?), I'll watch for changes after the AUR migration and try to contribute some doc if I can (or you don't beat me to it ;)

**Comment by grazzolini** [comment]
It's very likely that the default mkinitpio initramfs will be based on systemd rather than the base and udev hooks as it's today, in the near future. Also, it simplify a lot the dropbear deployment, I basically need to copy the binary and create a systemd unit inside the initramfs. Systemd starts and stops it. And for the network, I'm hoping to use the systemd-netword. The catch is making the encryptssh shell to work, last time I tried I had some problems. You'll need to install two packages, but I'll make the shell to require the dropbear hook, so only need to really install one of them.

**Comment by neitsab** [comment]
Very interesting, thanks!

Talking about systemd, have you also been hit by the [v219 series bug](https://bugs.archlinux.org/task/44658) that caused dropbear to fail on a `Device /dev/disk/by-id/wwn-XXX-partX doesn't exist or access denied` error (see my comment towards the end of the bug report)? I haven't been able to use version 219 at all and am still waiting on v220 to hit the stable repos to upgrade systemd, since Arch devs [refused to backport the patch](https://bugs.archlinux.org/task/45045) meanwhile...

Aren't you afraid that by making dropbear works more closely with the init this kind of situation will often repeat?

**Comment by grazzolini** [comment]
I wasn't hit by this bug. I don't use by-id to mount my partitions, I use only UUID. You could perhaps use it instead of by-id and see if you can use the latest systemd version. As for having this hook working with systemd, I don't think there will be problems. At least for starting dropbear. The remote shell is a different history altogether. But if Arch really does migrate to systemd initramfs, I will have to implement a systemd version.

**Comment by neitsab** [comment]
Indeed, using `by-id` for `cryptdevice:` kernel parameter and `crypttab` entries was the culprit. Changing those to standard `/dev/sdX#` naming scheme resolved my issues... Thanks!

Now I must report this upstream...
